# Task 1:

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.



In [1]:
def dividebyzero(dividend,divisor):
    try:
        return "Output of " + str(dividend) + '/' + str(divisor) + " is : " + str(dividend/divisor)
    except ZeroDivisionError:
        return "Encountered Zero Division Error please give divisor value greater than 0"

In [2]:
print(dividebyzero(5,1))
print(dividebyzero(5,0))

Output of 5/1 is : 5.0
Encountered Zero Division Error please give divisor value greater than 0


2.
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]

verbs=["play","watch"] 

objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball. 

Americans play Cricket. 

Americans watch Baseball. 

Americans watch Cricket. 

Indians play Baseball. 

Indians play Cricket. 

Indians watch Baseball. 

Indians watch Cricket.

In [3]:
subjects=["Americans","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

whole_sentence = [print(sub + " " + verb + " " + obj + ".") for sub in subjects for verb in verbs for obj in objects]

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


## Task 2:

1.
Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [4]:
def vanfunction(input_vector,N,inc_param):
    import numpy as np
    input = np.array(input_vector)
    return np.vander(input,N,increasing=inc_param)

In [5]:
print(vanfunction([4,3,2,1],4,True))
print(vanfunction([1,3,5,7],4,False))

[[ 1  4 16 64]
 [ 1  3  9 27]
 [ 1  2  4  8]
 [ 1  1  1  1]]
[[  1   1   1   1]
 [ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]]
